version: "3.1"
services:
  db:
    env_file: ./.env
    image: mariadb:10.5
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_USER" : ${MYSQL_USER}
      "MYSQL_PASSWORD": "${MYSQL_PASSWORD}"
      "MYSQL_DATABASE": "${MYSQL_DB}"
      "MYSQL_ROOT_PASSWORD": "${MYSQL_PASSWORD}"
  app:
    image: node:latest
    container_name: my-app
    working_dir: /usr/app/
    volumes:
      - .:/usr/app/
    depends_on:
      - db

    ports:
      - "8000:8000"
    entrypoint: /usr/app/docker_start.sh
    env_file: ./.env
    environment:
      "NODE_ENV": "development"